/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.GovernmentCoordinatorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.GovernmentOrganization;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ramsr
 */
public class GovernmentCoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentCoordinatorWorkAreaJPanel
     */
    private UserAccount userAccount;
    private GovernmentOrganization govtorganization;
    boolean a = true;
    DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public GovernmentCoordinatorWorkAreaJPanel(UserAccount account, GovernmentOrganization govtorganization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.system = system;
        this.userAccount = account;
        this.govtorganization = govtorganization;
        this.enterprise = enterprise;
        this.system = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userProcessContainer = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        BtnSelfProfile = new javax.swing.JLabel();
        BtnDonorStatus = new javax.swing.JLabel();
        BtnDonorRequests = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userProcessContainer.setBackground(new java.awt.Color(255, 153, 153));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        add(userProcessContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 930, 464));

        Header.setBackground(new java.awt.Color(15, 29, 52));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.GridLayout());

        BtnSelfProfile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSelfProfile.setForeground(new java.awt.Color(255, 255, 255));
        BtnSelfProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSelfProfile.setText("Edit Self Profile");
        BtnSelfProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSelfProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSelfProfileMouseClicked(evt);
            }
        });
        Header.add(BtnSelfProfile);

        BtnDonorStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnDonorStatus.setForeground(new java.awt.Color(255, 255, 255));
        BtnDonorStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnDonorStatus.setText("Check Donor Status");
        BtnDonorStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDonorStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDonorStatusMouseClicked(evt);
            }
        });
        Header.add(BtnDonorStatus);

        BtnDonorRequests.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnDonorRequests.setForeground(new java.awt.Color(255, 255, 255));
        BtnDonorRequests.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnDonorRequests.setText("Volunteer Donor Requests");
        BtnDonorRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDonorRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDonorRequestsMouseClicked(evt);
            }
        });
        Header.add(BtnDonorRequests);

        add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);    
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        
        if(numberbool == 1){
            
            h1.setBackground(new Color(70,55,37));
            h2.setBackground(new Color(216,99,1));        
        }
        else{
            h1.setBackground(new Color(216,99,1));
            h2.setBackground(new Color(70,55,37));   
        }  
    }
    
    private void BtnSelfProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSelfProfileMouseClicked
        // TODO add your handling code here:
        ManageGovernmentCoordinatorProfile manageGovtCoordinatorProfile = new ManageGovernmentCoordinatorProfile(userAccount,govtorganization,enterprise);
        userProcessContainer.add("ManageGovernmentCoordinatorProfile",manageGovtCoordinatorProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnSelfProfileMouseClicked

    private void BtnDonorStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDonorStatusMouseClicked
        // TODO add your handling code here:

        DonorStatusJPanel Profile = new DonorStatusJPanel(system);
        userProcessContainer.add("DonorStatusJPanel", Profile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnDonorStatusMouseClicked

    private void BtnDonorRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDonorRequestsMouseClicked
        // TODO add your handling code here:

        VolunteerDonorRequestJPanel Profile = new VolunteerDonorRequestJPanel(system);
        userProcessContainer.add("VolunteerDonorRequestJPanel", Profile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnDonorRequestsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnDonorRequests;
    private javax.swing.JLabel BtnDonorStatus;
    private javax.swing.JLabel BtnSelfProfile;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
